#!/bin/bash

if [ $(uname) == 'Linux' ]; then
echo "Compiling for Linux"
g++ -fPIC -Werror -pthread -O3 -shared -D__GLN__ component.cpp -o component.so -I"$HOME/usr/include" -I"/usr/include/brahms" -I"/var/lib/brahms/Namespace" -I"../../../../include" -I"$SYSTEMML_INSTALL_PATH/BRAHMS/include" -I"$SYSTEMML_INSTALL_PATH/Namespace" -L"$SYSTEMML_INSTALL_PATH/BRAHMS/bin"
else
echo "Compiling for OSX"
g++ -fvisibility=hidden -fvisibility-inlines-hidden -arch x86_64 -D__OSX__ -DARCH_BITS=32 -fPIC -O3 -ffast-math -dynamiclib -fno-strict-aliasing -arch i386 -D__OSX__ component.cpp -o component.dylib -I"$SYSTEMML_INSTALL_PATH/BRAHMS/include" -I"../../../../include" -I"$SYSTEMML_INSTALL_PATH/Namespace" -L"$SYSTEMML_INSTALL_PATH/BRAHMS/bin" -lbrahms-engine
fi


#g++ -fvisibility=hidden -fvisibility-inlines-hidden -arch x86_64 -D__OSX__ -DARCH_BITS=32 -fPIC -Werror -Wall -ffast-math -arch i386 -Wfatal-errors -fno-strict-aliasing -arch x86_64 -O3 -I/Applications/SystemML//BRAHMS/include -I/Applications/SystemML//Namespace -dynamiclib -D__REL__=0 -D__REV__=-1 -DBRAHMS_NO_LEGACY_SUPPORT data_numeric.cpp -o /Applications/SystemML//Namespace/std/2009/data/numeric/brahms/0/component.dylib -L/Applications/SystemML//BRAHMS/bin -L/Users/alex/btmp/ -lbrahms-engine
