<?xml version="1.0" encoding="ISO-8859-1"?><xsl:stylesheet version="1.0"
xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
xmlns:fn="http://www.w3.org/2005/xpath-functions" exclude-result-prefixes="fn">
<xsl:output method="xml" omit-xml-declaration="no" version="1.0" encoding="UTF-8" indent="yes"/>

<!--
     This template adds the Processes and Links necessary to connect
     in the Patra-developed biomechanical arm model.

     Currently, this DEPENDS on the SpineML model being the
     ABRG-Models/linetask model.

     It also requires that the user has compiled the armsimulator
     code, including the component.so BRAHMS component, and installed
     that in dev/NoTremor/armsimulator within the BRAHMS Namespace
     dirs that are being used by SpineML_2_BRAHMS.
-->

<xsl:param name="spineml_output_dir" select="'./'"/>

<!-- START TEMPLATE -->
<xsl:template name="armsim">

<xsl:comment>Generated by Armsim.xsl</xsl:comment>

<!-- GET A LINK TO THE EXPERIMENT FILE FOR LATER USE -->
<xsl:variable name="expt_root" select="/"/>

<!-- GET THE SAMPLE RATE -->
<xsl:variable name="sampleRate" select="(1 div number($expt_root//@dt)) * 1000.0"/>

<!-- This is the destination process - the Arm simulator itself. -->
<Process>
	<Name>Armsim</Name>
	<Class>dev/NoTremor/armsimulator</Class>
	<State c="z" a="model_path;initial_state_path;end_effector_body;result_dir;end_effector_offset_x;end_effector_offset_y;end_effector_offset_z;use_muscle_controller;use_dual_channe;use_elbow_constraint;" Format="DataML" Version="5" AuthTool="SystemML Toolbox" AuthToolVersion="0">
		<m>/home/seb/src/armsimulator/data/models/Stanford VA upper limb model/NoTremor Upper Limb Model6.osim</m>
		<m></m> <!-- Options: "", path -->
		<m>hand</m>
		<m>/home/seb/src/armsimulator/data/results/armsimulation</m>
		<m c="d">0.05</m>
		<m c="d">-0.14</m>
		<m c="d">0.011</m>
		<m c="d">0</m>
		<m c="d">0</m>
		<m c="d">0</m>
	</State>
</Process>

<Process>
	<Name>ZeroInput</Name>
	<Class>std/2009/source/numeric</Class>
	<Time><SampleRate>1000</SampleRate></Time>
	<State c="z" a="data;repeat;" Format="DataML" Version="5" AuthTool="SystemML Toolbox" AuthToolVersion="0">
		<m b="1 1" c="d">0</m>
		<m c="l">1</m>
	</State>
</Process>

<!-- Here, we link each channel input activity process to the arm simulator. -->
<Link>
  <Src>ZeroInput&gt;out</Src>
  <Dst>Armsim&lt;&lt;&lt;accelerationCh1X</Dst>
  <Lag>0</Lag>
</Link>
<Link>
  <Src>ZeroInput&gt;out</Src>
  <Dst>ArmSimulator&lt;&lt;&lt;accelerationCh1Y</Dst>
  <Lag>0</Lag>
</Link>
<Link>
  <Src>IntegrateJ&gt;a</Src>
  <Dst>ArmSimulator&lt;&lt;&lt;accelerationCh1Z</Dst>
  <Lag>0</Lag>
</Link>

<Link>
  <Src>ZeroInput&gt;out</Src>
  <Dst>ArmSimulator&lt;&lt;&lt;accelerationCh2X</Dst>
  <Lag>0</Lag>
</Link>
<Link>
  <Src>ZeroInput&gt;out</Src>
  <Dst>ArmSimulator&lt;&lt;&lt;accelerationCh2Y</Dst>
  <Lag>0</Lag>
</Link>
<Link>
  <Src>IntegrateJ&gt;a</Src>
  <Dst>ArmSimulator&lt;&lt;&lt;accelerationCh2Z</Dst>
  <Lag>0</Lag>
</Link>


<!-- Position from Armsim is fed into X population -->
<Link>
	<Src>Armsim&gt;endEffectorPositionX</Src>
	<Dst>Xpopulation&lt;&lt;&lt;rx</Dst>
	<Lag>0</Lag>
</Link>
<Link>
	<Src>Armsim&gt;endEffectorPositionY</Src>
	<Dst>Xpopulation&lt;&lt;&lt;ry</Dst>
	<Lag>0</Lag>
</Link>
<Link>
	<Src>Armsim&gt;endEffectorPositionZ</Src>
	<Dst>Xpopulation&lt;&lt;&lt;rz</Dst>
	<Lag>0</Lag>
</Link>

<!-- Velocity from Armsim is fed into X population -->
<Link>
	<Src>Armsim&gt;endEffectorVelocityX</Src>
	<Dst>Xpopulation&lt;&lt;&lt;vx</Dst>
	<Lag>0</Lag>
</Link>
<Link>
	<Src>Armsim&gt;endEffectorVelocityY</Src>
	<Dst>Xpopulation&lt;&lt;&lt;vy</Dst>
	<Lag>0</Lag>
</Link>
<Link>
	<Src>Armsim&gt;endEffectorVelocityZ</Src>
	<Dst>Xpopulation&lt;&lt;&lt;vz</Dst>
	<Lag>0</Lag>
</Link>

<!-- Acceleration from Armsim is fed into X population -->
<Link>
	<Src>Armsim&gt;endEffectorAccelerationX</Src>
	<Dst>Xpopulation&lt;&lt;&lt;ax</Dst>
	<Lag>0</Lag>
</Link>
<Link>
	<Src>Armsim&gt;endEffectorAccelerationY</Src>
	<Dst>Xpopulation&lt;&lt;&lt;ay</Dst>
	<Lag>0</Lag>
</Link>
<Link>
	<Src>Armsim&gt;endEffectorAccelerationZ</Src>
	<Dst>Xpopulation&lt;&lt;&lt;az</Dst>
	<Lag>0</Lag>
</Link>

<!-- END TEMPLATE -->
</xsl:template>

</xsl:stylesheet>
