<?xml version="1.0" encoding="ISO-8859-1"?><xsl:stylesheet version="1.0"
xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
xmlns:fn="http://www.w3.org/2005/xpath-functions" exclude-result-prefixes="fn">
<xsl:output method="xml" omit-xml-declaration="no" version="1.0" encoding="UTF-8" indent="yes"/>

<!--
     This template adds the Processes and Links necessary to connect
     the centroid output of the powercentroid, its centroid sum and
     the rotations to SCA, X and worldDataMaker, respectively.
-->

<xsl:param name="spineml_output_dir" select="'./'"/>

<!-- START TEMPLATE -->
<xsl:template name="eyeless">

<xsl:comment>Generated by eyeless.xsl</xsl:comment>

<!-- GET A LINK TO THE EXPERIMENT FILE FOR LATER USE -->
<xsl:variable name="expt_root" select="/"/>

<!-- GET THE SAMPLE RATE -->
<xsl:variable name="sampleRate" select="(1 div number($expt_root//@dt)) * 1000.0"/>

<!-- GET A LINK TO THE NETWORK FILE FOR LATER USE -->
<!-- <xsl:variable name="main_root" select="/"/> -->

<!-- This is the world data maker process. Centroid rotations into this process. -->
<Process>
	<Name>WorldDataMaker</Name>
	<Class>dev/NoTremor/worldDataMaker</Class>
	<State c="z" a="output_data_path;neuronsPerPopulation;" Format="DataML" Version="5" AuthTool="SystemML Toolbox" AuthToolVersion="0">
		<m><xsl:value-of select="$spineml_output_dir"/></m>
                <m c="f">2500</m>
	</State>
	<Time><SampleRate><xsl:value-of select="$sampleRate"/></SampleRate></Time>
	<State></State>
</Process>

<!-- The pseudo eye component -->
<Process>
	<Name>pseudoeye</Name>
	<Class>dev/NoTremor/pseudoeye</Class>
	<State c="z" a="output_data_path;threshold;power_degree;settleTime;" Format="DataML" Version="5" AuthTool="SystemML Toolbox" AuthToolVersion="0">
                <m><xsl:value-of select="$spineml_output_dir"/></m>
		<m c="f">0.9</m>
                <m c="f">2</m>
                <m c="f">120</m>
	</State>
	<Time><SampleRate><xsl:value-of select="$sampleRate"/></SampleRate></Time>
	<State></State>
</Process>

<!-- From SC_deep we feed pseudoeye... -->
<Link>
	<Src>SC_deep&gt;out</Src>
	<Dst>pseudoeye&lt;&lt;&lt;inputSheet</Dst>
	<Lag>0</Lag>
</Link>

<!-- Output from pseudoeye is fed into the SC_avg population for easy
     logging -->
<Link>
	<Src>pseudoeye&gt;centroid</Src>
	<Dst>SC_avg&lt;in</Dst>
	<Lag>1</Lag>
</Link>

<!-- theoretical rotations output from pseudeye is input to WorldDataMaker component -->
<Link>
	<Src>pseudoeye&gt;rotationsOut</Src>
	<Dst>WorldDataMaker&lt;&lt;&lt;rotationsIn</Dst>
	<Lag>0</Lag>
</Link>

<!-- Output from WorldDataMaker is fed into the World population, which
     then gates this with MN output and feeds it into Retina_1 and Retina_2 -->
<Link>
	<Src>WorldDataMaker&gt;corticalSheet</Src>
	<Dst>World&lt;in</Dst>
	<Lag>0</Lag>
</Link>

<!-- END TEMPLATE -->
</xsl:template>

</xsl:stylesheet>
