<?xml version="1.0" encoding="ISO-8859-1"?><xsl:stylesheet version="1.0"
xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
xmlns:fn="http://www.w3.org/2005/xpath-functions" exclude-result-prefixes="fn">
<xsl:output method="xml" omit-xml-declaration="no" version="1.0" encoding="UTF-8" indent="yes"/>

<!--
     This template adds the Processes and Links necessary to connect
     in the Patra-developed and Seb-brahms-wrapped biomechanical eye
     model.

     Currently, this DEPENDS on the SpineML model being the
     Oculormotor model with saccade generator and on correct naming of
     the outputs of the saccade generator (MN up/down, MN left/right)

     It also requires that the user has compiled the saccsim code,
     including the component.so BRAHMS component, and installed that
     in dev/NoTremor/saccsim within the BRAHMS Namespace dirs that are
     being used by SpineML_2_BRAHMS.
-->

<xsl:param name="spineml_output_dir" select="'./'"/>

<!-- START TEMPLATE -->
<xsl:template name="saccsimOculomotor">

<xsl:comment>Generated by Saccsim_Oculomotor.xsl</xsl:comment>

<!-- GET A LINK TO THE EXPERIMENT FILE FOR LATER USE -->
<xsl:variable name="expt_root" select="/"/>

<!-- GET THE SAMPLE RATE -->
<xsl:variable name="sampleRate" select="(1 div number($expt_root//@dt)) * 1000.0"/>

<!-- GET A LINK TO THE NETWORK FILE FOR LATER USE -->
<!-- <xsl:variable name="main_root" select="/"/> -->

<!-- This is the destination process - the Saccade simulator itself. -->
<Process>
	<Name>SaccSim</Name>
	<Class>dev/NoTremor/saccsim</Class>
	<State c="z" a="output_data_path;" Format="DataML" Version="5" AuthTool="SystemML Toolbox" AuthToolVersion="0">
		<m><xsl:value-of select="$spineml_output_dir"/></m>
	</State>
	<Time><SampleRate><xsl:value-of select="$sampleRate"/></SampleRate></Time>
	<State></State>
</Process>

<Process>
	<Name>Zeroes</Name>
	<Class>std/2009/source/numeric</Class>
	<Time><SampleRate><xsl:value-of select="$sampleRate"/></SampleRate></Time>
	<State c="z" a="data;repeat;" Format="DataML" Version="5" AuthTool="SystemML Toolbox" AuthToolVersion="0">
		<m b="1 1" c="d">0</m>
		<m c="l">1</m>
	</State>
</Process>

<!-- Here, we link each muscle input activity process to the Saccade simulator. -->
<Link>
	<Src>MN_up&gt;a</Src>
	<Dst>SaccSim&lt;&lt;&lt;suprect</Dst>
	<Lag>0</Lag>
</Link>
<Link>
	<Src>MN_down&gt;a</Src>
	<Dst>SaccSim&lt;&lt;&lt;infrect</Dst>
	<Lag>0</Lag>
</Link>
<Link>
	<Src>MN_right&gt;a</Src>
	<Dst>SaccSim&lt;&lt;&lt;medrect</Dst>
	<Lag>0</Lag>
</Link>
<Link>
	<Src>MN_left&gt;a</Src>
	<Dst>SaccSim&lt;&lt;&lt;latrect</Dst>
	<Lag>0</Lag>
</Link>
<Link>
	<Src>Zeroes&gt;out</Src>
	<Dst>SaccSim&lt;&lt;&lt;supobl</Dst>
	<Lag>0</Lag>
</Link>
<Link>
	<Src>Zeroes&gt;out</Src>
	<Dst>SaccSim&lt;&lt;&lt;infobl</Dst>
	<Lag>0</Lag>
</Link>

<!-- END TEMPLATE -->
</xsl:template>

</xsl:stylesheet>
